{
 "title": "service monitor backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"service_monitor_backend\",instance=\"service-monitor-backend:8081\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"service_monitor_backend\"}[1m]))\r\n",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"service_monitor_backend\",status=~\"5..\"}[1m]))\r\n",
     "legendFormat": "5xx Error RPS"
    }
   ]
  },
  {
   "title": "JVM Heap Used ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"service_monitor_backend\",area=\"heap\"})\r\n",
     "legendFormat": "Heap Used"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"service_monitor_backend\",area=\"nonheap\"})\r\n",
     "legendFormat": "Non Heap Used"
    }
   ]
  },
  {
   "title": "Live JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"service_monitor_backend\"}\r\n",
     "legendFormat": "Live Threads"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"service_monitor_backend\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service monitor dashboard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "up{job='service_monitor_backend'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}