-- Step 3 hardening: deterministic writer source semantics.
-- Mark rows generated by the Python writer as POPULATOR and allow that in constraints.

ALTER TABLE monitoring.service_availability_events
    DROP CONSTRAINT IF EXISTS chk_service_availability_source;

ALTER TABLE monitoring.service_availability_events
    ADD CONSTRAINT chk_service_availability_source
        CHECK (source IN ('PROMETHEUS', 'GRAFANA', 'MANUAL', 'POPULATOR'));

ALTER TABLE monitoring.http_error_events
    DROP CONSTRAINT IF EXISTS chk_http_error_source;

ALTER TABLE monitoring.http_error_events
    ADD CONSTRAINT chk_http_error_source
        CHECK (source IN ('PROMETHEUS', 'GRAFANA', 'MANUAL', 'SIMULATION', 'POPULATOR'));

ALTER TABLE monitoring.alert_events
    DROP CONSTRAINT IF EXISTS chk_alert_source;

ALTER TABLE monitoring.alert_events
    ADD CONSTRAINT chk_alert_source
        CHECK (alert_source IN ('GRAFANA', 'PROMETHEUS', 'POPULATOR'));
